// Code generated by hertz generator.

package book

import (
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/common/config"
)

type BookServiceClient struct {
	client *client.Client
}

func NewBookServiceClient(opt ...config.ClientOption) (*BookServiceClient, error) {
	c, err := client.NewClient(opt...)
	if err != nil {
		return nil, err
	}

	return &BookServiceClient{
		client: c,
	}, nil
}
