// Code generated by Validator v0.1.4. DO NOT EDIT.

package user

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *User) IsValid() error {
	return nil
}
func (p *SignupRequest) IsValid() error {
	return nil
}
func (p *LoginRequest) IsValid() error {
	return nil
}
func (p *LoginResponse) IsValid() error {
	return nil
}
func (p *LogoutRequest) IsValid() error {
	return nil
}
func (p *LogoutResponse) IsValid() error {
	return nil
}
func (p *GetUserRequest) IsValid() error {
	return nil
}
func (p *GetUserResponse) IsValid() error {
	return nil
}
func (p *GetUserMeRequest) IsValid() error {
	return nil
}
func (p *GetUserMeResponse) IsValid() error {
	return nil
}
