// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/common/config"
)

type UserServiceClient struct {
	client *client.Client
}

func NewUserServiceClient(opt ...config.ClientOption) (*UserServiceClient, error) {
	c, err := client.NewClient(opt...)
	if err != nil {
		return nil, err
	}

	return &UserServiceClient{
		client: c,
	}, nil
}
