// Code generated by hertz generator.

package book

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/three-body/hertz-scaffold/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _booksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbooksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbookMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
	}
}

func _updatebookMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
	}
}

func _renamebookMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
	}
}

func _deletebookMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
	}
}
