package config

// generate by https://printlove.cn/tools/yaml2go

type AutoGenerated struct {
	Logger  Logger  `yaml:"logger"`
	Hertz   Hertz   `yaml:"hertz"`
	Swagger Swagger `yaml:"swagger"`
	Mysql   Mysql   `yaml:"mysql"`
}

type Logger struct {
	LogMaxBackups int    `yaml:"logMaxBackups"`
	Level         string `yaml:"level"`
	Stdout        bool   `yaml:"stdout"`
	LogFileName   string `yaml:"logFileName"`
	LogMaxSize    int    `yaml:"logMaxSize"`
	LogMaxAge     int    `yaml:"logMaxAge"`
}

type Hertz struct {
	EnableAccessLog bool   `yaml:"enableAccessLog"`
	ExitWaitTime    int    `yaml:"exitWaitTime"`
	Address         string `yaml:"address"`
	EnablePprof     bool   `yaml:"enablePprof"`
}

type Swagger struct {
	BasePath string `yaml:"basePath"`
	Schemes  string `yaml:"Schemes"`
	Enable   bool   `yaml:"enable"`
	Version  string `yaml:"version"`
	Host     string `yaml:"host"`
}

type Mysql struct {
	ConnMaxOpen               int      `yaml:"connMaxOpen"`
	ConnMaxLifeTime           int      `yaml:"connMaxLifeTime"`
	Separation                bool     `yaml:"separation"`
	Master                    string   `yaml:"master"`
	Slave                     []string `yaml:"slave"`
	DefaultStringSize         int      `yaml:"defaultStringSize"`
	DisableDatetimePrecision  bool     `yaml:"disableDatetimePrecision"`
	ConnMaxIdle               int      `yaml:"connMaxIdle"`
	ConnMaxIdleTime           int      `yaml:"connMaxIdleTime"`
	SkipInitializeWithVersion bool     `yaml:"skipInitializeWithVersion"`
	Gorm                      Gorm     `yaml:"gorm"`
}

type Gorm struct {
	IgnoreRecordNotFoundError bool `yaml:"ignoreRecordNotFoundError"`
	SlowThreshold             int  `yaml:"slowThreshold"`
	SkipDefaultTx             bool `yaml:"skipDefaultTx"`
	PrepareStmt               bool `yaml:"prepareStmt"`
}
