// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	ID        uint64                `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	Title     string                `gorm:"column:title;not null;comment:title" json:"title"`
	Author    string                `gorm:"column:author;not null;comment:author" json:"author"`
	Pages     int                   `gorm:"column:pages;not null;comment:page num of book" json:"pages"`
	CreatedAt *time.Time            `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:created time" json:"created_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:updated time" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:deleted time" json:"deleted_at"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
