// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          uint64                                `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	UID         string                                `gorm:"column:uid;not null;comment:uid" json:"uid"`
	Username    string                                `gorm:"column:username;not null;comment:username" json:"username"`
	Nickname    string                                `gorm:"column:nickname;not null;comment:nickname" json:"nickname"`
	Description string                                `gorm:"column:description;not null;comment:description" json:"description"`
	Email       string                                `gorm:"column:email;not null;comment:email" json:"email"`
	Phone       string                                `gorm:"column:phone;not null;comment:phone" json:"phone"`
	Extra       datatypes.JSONType[map[string]string] `gorm:"column:extra;not null;comment:extra" json:"extra"`
	CreatedAt   *time.Time                            `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:created time" json:"created_at"`
	UpdatedAt   *time.Time                            `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:updated time" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt                 `gorm:"column:deleted_at;not null;comment:deleted time" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
