// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint64                `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	UID       string                `gorm:"column:uid;not null;comment:uid" json:"uid"`
	Email     string                `gorm:"column:email;not null;comment:email" json:"email"`
	Password  string                `gorm:"column:password;not null;comment:password" json:"password"`
	Nickname  string                `gorm:"column:nickname;not null;comment:nickname" json:"nickname"`
	CreatedAt *time.Time            `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:created time" json:"created_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:updated time" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:deleted time;softDelete:milli" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
